name: Build, Test, Push to Docker Hub

on:
  push:
    branches: [ master ]
    paths:
      - 'server/**'
      - 'mongodb/Dockerfile'
      - '.github/workflows/main.yml'

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Run tests with HTML report
        run: |
          pytest
        continue-on-error: false

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/report.html    

  docker_hub:
    name: Push Docker image to Docker Hub
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push python Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/diet-server:latest
 
      - name: Build and push mongodb Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./mongodb
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/diet-database:latest

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.sha }}